name: phpunit

on:
  push:
  pull_request:

jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ["8.4", "8.3", "8.2", "8.1", "8.0"]
        dependency-version: ["prefer-lowest", "prefer-stable"]
        exclude:
          - php: "8.4"
            dependency-version: "prefer-lowest"
          - php: "8.3"
            dependency-version: "prefer-lowest"
          - php: "8.2"
            dependency-version: "prefer-lowest"
          - php: "8.1"
            dependency-version: "prefer-lowest"

    name: P${{ matrix.php }} - ${{ matrix.dependency-version }}

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip
          tools: composer:v2

      - run: composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

      - run: vendor/bin/phpunit
