name: pint

on:
  push:
  pull_request:

jobs:
  pint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: dom, curl, libxml, mbstring, zip
          tools: composer:v2

      - run: composer install --prefer-dist --no-interaction

      - run: vendor/bin/pint --test
